language: cpp

dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y doxygen

# sudo: required

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./apps/myapp
  
